kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx-sample
spec:
  ingressClassName: openshift-default
  rules:
  - host: "example.apps.cluster-dvhfl.dvhfl.sandbox2065.opentlc.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-sample-service
            port:
              number: 8080
